name: test
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.18
    steps:
      - run: apk add --no-cache wget tar xz git
      - uses: actions/checkout@v3
      - run: >
          wget -O-
          https://github.com/koalaman/shellcheck/releases/download/v0.9.0/shellcheck-v0.9.0.linux.x86_64.tar.xz
          | tar xJ --strip-components=1 --wildcards -C /usr/local/bin '*/shellcheck'
      - run: shellcheck sbin/* spec/* test/*
  shellspec:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.18
    steps:
      - run: apk add --no-cache wget git
      - uses: actions/checkout@v3
      - run: wget -O- https://git.io/shellspec | sh -s -- 0.28.1 -p /usr/local -y
      - run: shellspec
  integration:
    runs-on: ubuntu-latest
    container:
      image: alpine:3.18
      options: --privileged
    steps:
      - run: apk add --no-cache wget git e2fsprogs cryptsetup util-linux
      # Remove the busybox setpriv. It hides the one from util-linux (/usr/bin)
      # as the $PATH order is different. Changing the shebang to run the helper
      # using a login shell also fixes the problem. Note that this removal must
      # be done after 'apk add' call.
      - run: rm /bin/setpriv
      - uses: actions/checkout@v3
      - run: ln -s "$(pwd)/sbin/"* /sbin
      - run: wget -O- https://git.io/shellspec | sh -s -- 0.28.1 -p /usr/local -y
      - run: test/integration.sh
